[PackageColumns]
# 包号/件号的识别名称，用逗号分隔
names = 包号,件号,Roll No,Package No,卷号,编号

[FormatOptions]
# 是否在单元格内容前添加前缀，true为启用，false为禁用
add_prefixes = true
# 是否需要实际码长，true为需要，false为不需要
include_actual_length = false
# 最小分数
min_score = 5
# 最大分数
max_score = 14
# 计分项目数量
score_items_count = 22
# 总扣分和其他之间的空行数量
empty_lines_between_total_and_other = 1